### ISSUE TITLE
SonarCloud beüzemelése és kódanalízis

### ISSUE THREAD

**Issue by KrisztianBui** [BME-MIT-IET/iet-hf-2023-bpsztnob#3]
A SonarCloud-hoz kéne kapcsolni a projektet, és az analízis alapján ki kell javítani a hibákat, code smell-eket.

**Comment by KrisztianBui** [comment]
Hozzáadtam a SonarCloud ellenőrzőt. A hibákat ki kell még javítani.

**Comment by TheThigor** [comment]
Megtaláltam, valamikor neki állok.
