### ISSUE TITLE
Cucumber keretrendszer beüzemelése és tesztek megírása

### ISSUE THREAD

**Issue by KrisztianBui** [BME-MIT-IET/iet-hf-2023-bpsztnob#5]
A Maven-hez hozzá kell adni a Cucumber-t, utána go tesztek megoldása.

![](https://i.ytimg.com/vi/EVOehHbULQE/hqdefault.jpg)

**Comment by TheThigor** [comment]
Írtam teszteket, a UseEquipmentCommandra nézzünk rá, mert szerintem valami nem jó benne
